const oracledb = require('oracledb');
try {
    oracledb.initOracleClient({ libDir: '/opt/oracle/instantclient_21_12' });
} catch (err) { }
const fs = require('fs');
const path = require('path');

const TABLES = [
    `CREATE TABLE CANAL_ANALISE_CNPJ (
        CODCLI NUMBER PRIMARY KEY,
        CGCENT VARCHAR2(20),
        SITUACAO_CADASTRAL VARCHAR2(100),
        ATUALIZADO_POR VARCHAR2(50),
        DATA_ANALISE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE CANAL_ANALISE_IE (
        CODCLI NUMBER PRIMARY KEY,
        CNPJ VARCHAR2(20),
        IE_SISTEMA VARCHAR2(50),
        UF_SISTEMA VARCHAR2(2),
        SITUACAO_IE VARCHAR2(100),
        IE_NOVA VARCHAR2(50),
        ATUALIZADO_POR VARCHAR2(50),
        DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE CANAL_MENSAGENS (
        ID_MENSAGEM VARCHAR2(255) PRIMARY KEY,
        CODUSUR VARCHAR2(50),
        TELEFONE_CLIENTE VARCHAR2(50),
        SENTIDO VARCHAR2(20),
        TEXTO CLOB,
        DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        MEDIA_URL VARCHAR2(1000),
        MEDIA_TYPE VARCHAR2(50),
        MEDIA_MIMETYPE VARCHAR2(100),
        ARQUIVO_LOCAL VARCHAR2(1000),
        STATUS VARCHAR2(50),
        LIDA CHAR(1) DEFAULT 'N',
        TICKET_ID NUMBER
    )`,
    `CREATE TABLE CANAL_TOKENS_EVOLUTION (
        CODUSUR VARCHAR2(50) PRIMARY KEY,
        INSTANCE_NAME VARCHAR2(100),
        API_TOKEN VARCHAR2(255),
        API_URL VARCHAR2(255),
        NOME_ATENDENTE VARCHAR2(100),
        STATUS VARCHAR2(50),
        DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE JCWEBHOOK (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        DT_REQUISICAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONTEUDO CLOB,
        ORIGEM VARCHAR2(50) DEFAULT 'whats'
    )`,
    `CREATE TABLE CANAL_WEBHOOK_STATE (
        ID NUMBER PRIMARY KEY,
        LAST_PROCESSED_ID NUMBER DEFAULT 0
    )`,
    `CREATE TABLE CANAL_CONFIGURACOES (
        CHAVE VARCHAR2(100) PRIMARY KEY,
        VALOR VARCHAR2(4000)
    )`,
    `CREATE TABLE CANAL_ROTAS (
        CODUSUR VARCHAR2(50),
        DIASEMANA NUMBER,
        CODCLI NUMBER,
        SEQUENCIA NUMBER,
        INTERACAO VARCHAR2(100),
        PRIMARY KEY (CODUSUR, DIASEMANA, CODCLI)
    )`,
    `CREATE TABLE CANAL_AGENDAMENTO_STATUS (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        ARQUIVO_PATH VARCHAR2(255),
        LEGENDA VARCHAR2(4000),
        DATA_PROGRAMADA TIMESTAMP,
        VENDEDORES_DESTINO CLOB,
        CRIADO_POR VARCHAR2(50),
        STATUS_ENVIO VARCHAR2(50) DEFAULT 'PENDENTE'
    )`,
    `CREATE TABLE CANAL_LOG_ALTERACAO_VENDEDOR (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        CODCLI NUMBER,
        VENDEDOR_ANTERIOR VARCHAR2(50),
        VENDEDOR_NOVO VARCHAR2(50),
        ALTERADO_POR VARCHAR2(50),
        DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE CANAL_REATIVACAO_FILA (
        ID NUMBER PRIMARY KEY,
        CODCLI NUMBER,
        TELEFONE VARCHAR2(50),
        CODUSUR VARCHAR2(50),
        MENSAGEM_TXT CLOB,
        CODATV1 NUMBER,
        STATUS VARCHAR2(50),
        DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        DATA_PROCESSAMENTO TIMESTAMP,
        LOG_ERRO CLOB
    )`,
    `CREATE TABLE CANAL_TEMPLATES (
        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TITULO VARCHAR2(100),
        TEXTO CLOB
    )`,
    `CREATE TABLE CANAL_AVISOS (
        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TEXTO CLOB,
        CODUSUR_REMETENTE VARCHAR2(50),
        DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE CANAL_VISITAS (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        CODCLI NUMBER,
        CODUSUR VARCHAR2(50),
        TIPO_MENSAGEM VARCHAR2(50),
        DATA_AGENDADA TIMESTAMP,
        CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        STATUS VARCHAR2(50),
        OBSERVACAO VARCHAR2(4000),
        LATITUDE NUMBER,
        LONGITUDE NUMBER,
        ENDERECO_VINCULADO VARCHAR2(4000),
        IMAGEM_URL VARCHAR2(4000),
        RETORNO VARCHAR2(4000),
        SINALIZADO_VENDEDOR CHAR(1) DEFAULT 'N'
    )`,
    `CREATE TABLE CANAL_MENSAGENS_AUT_CONFIG (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        TIPO_REGRA VARCHAR2(100),
        DIAS_GATILHO NUMBER,
        DIA_ESPECIFICO NUMBER,
        TEMPLATE_MENSAGEM CLOB,
        ATIVO CHAR(1) DEFAULT 'S'
    )`,
    `CREATE TABLE CANAL_WHATSAPP_CACHE (
        TELEFONE VARCHAR2(50) PRIMARY KEY,
        TEM_WHATS CHAR(1),
        DATA_VERIFICACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE CANAL_BOT_STATE (
        TELEFONE VARCHAR2(50) PRIMARY KEY,
        ESTADO_ATUAL VARCHAR2(100),
        DADOS_TEMPORARIOS CLOB,
        ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE CANAL_SAC_DEPARTAMENTOS (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        NOME VARCHAR2(100),
        DEPARTAMENTO_PAI_ID NUMBER,
        ATIVO CHAR(1) DEFAULT 'S'
    )`,
    `CREATE TABLE CANAL_SAC_TICKETS (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        TELEFONE VARCHAR2(50),
        CODCLI NUMBER,
        DEPARTAMENTO_ID NUMBER,
        DESCRICAO CLOB,
        STATUS VARCHAR2(50) DEFAULT 'ABERTO',
        CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        ATUALIZADO_EM TIMESTAMP,
        DATA_RESOLUCAO TIMESTAMP
    )`,
    `CREATE TABLE CANAL_PROSPECTS (
        ID VARCHAR2(50) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
        NOME_FANTASIA VARCHAR2(255) NOT NULL,
        RAZAO_SOCIAL VARCHAR2(255),
        CNPJ VARCHAR2(20),
        TELEFONE VARCHAR2(100),
        ENDERECO VARCHAR2(500),
        CIDADE VARCHAR2(100),
        ESTADO VARCHAR2(2),
        LATITUDE VARCHAR2(50),
        LONGITUDE VARCHAR2(50),
        ORIGEM VARCHAR2(50),
        RAMO_ATIVIDADE VARCHAR2(100),
        HAS_WHATSAPP VARCHAR2(1) DEFAULT 'P',
        DATA_CADASTRO DATE DEFAULT SYSDATE
    )`,
    `CREATE TABLE CANAL_LOG_IDENTIFICACAO_CLIENTE (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        TELEFONE VARCHAR2(20),
        DOCUMENTO_INFORMADO VARCHAR2(50),
        CODCLI_LOCALIZADO NUMBER,
        OPCAO_USADA VARCHAR2(100),
        DATA_HORA DATE DEFAULT SYSDATE
    )`,
    `CREATE TABLE CANAL_MENSAGENS_TEMPLATES (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        PAGINA VARCHAR2(50) NOT NULL,
        TIPO VARCHAR2(100) NOT NULL,
        TEMPLATE VARCHAR2(4000) NOT NULL
    )`
];

async function initializeOracleDatabase() {
    console.log('🚀 [STARTUP] Iniciando verificação estrutural do banco Oracle...');
    let conn;
    try {
        conn = await oracledb.getConnection({
            user: process.env.ORACLE_USER,
            password: process.env.ORACLE_PASS,
            connectString: process.env.ORACLE_CONN_STR
        });

        // DROP TABLE removido para não apagar dados em todo restart

        // 1. Criar Tabelas
        for (const sql of TABLES) {
            try {
                await conn.execute(sql);
                const tableName = sql.match(/CREATE TABLE (\w+)/)[1];
                console.log(`✅ [STARTUP] Tabela ausente criada com sucesso: ${tableName}`);
            } catch (err) {
                // Erro 955: "name is already used by an existing object"
                if (err.errorNum === 955) {
                    // Ignora, já existe
                } else {
                    console.error(`❌ [STARTUP] Erro ao criar tabela:\n${sql}\nDetalhe do Erro:`, err.message);
                }
            }
        }

        // 2. Criar Views
        const viewsFilePath = path.join(__dirname, '../database/winthor_views.sql');
        if (fs.existsSync(viewsFilePath)) {
            let viewsSql = fs.readFileSync(viewsFilePath, 'utf8');
            
            // Remove comentários SQL de linha dupla (--) e blocos (/* */) para o parser não se perder
            viewsSql = viewsSql.replace(/--.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');

            // Split por ';'
            const statements = viewsSql.split(';').map(s => s.trim()).filter(s => s.length > 0);
            
            for (const stmt of statements) {
                if (stmt.toUpperCase().startsWith('CREATE')) {
                    try {
                        await conn.execute(stmt);
                    } catch (err) {
                        console.error(`⚠️ [STARTUP] Erro ao recriar view: ${stmt.substring(0, 50)}...`, err.message);
                    }
                }
            }
            console.log('✅ [STARTUP] Todas as Views do Winthor (VW_CANAL_*) foram mapeadas com sucesso.');
        } else {
            console.warn('⚠️ [STARTUP] Aviso: Arquivo winthor_views.sql não encontrado.');
        }

        // 2.1 Criar Views Nativas
        try {
            const sqlView = `
            CREATE OR REPLACE VIEW VW_TICKETS_COM_HISTORICO AS
            SELECT 
                t.ID AS TICKET_ID,
                t.TELEFONE,
                t.STATUS,
                t.CRIADO_EM,
                (
                    SELECT LISTAGG(
                        CASE 
                            WHEN m.SENTIDO = 'IN' THEN 'Cliente: ' || m.TEXTO
                            ELSE 'Atendente: ' || m.TEXTO
                        END, CHR(10)
                    ) WITHIN GROUP (ORDER BY m.DATA_HORA)
                    FROM CANAL_MENSAGENS m
                    WHERE m.TICKET_ID = t.ID
                ) AS HISTORICO_ATENDIMENTO
            FROM 
                CANAL_SAC_TICKETS t
            `;
            await conn.execute(sqlView);
            console.log('✅ [STARTUP] View VW_TICKETS_COM_HISTORICO criada/atualizada com sucesso.');
        } catch(err) {
            console.error('⚠️ [STARTUP] Erro ao criar view VW_TICKETS_COM_HISTORICO:', err.message);
        }

        // Initialize state table if empty
        try {
            await conn.execute(`INSERT INTO CANAL_WEBHOOK_STATE (ID, LAST_PROCESSED_ID) SELECT 1, 0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CANAL_WEBHOOK_STATE WHERE ID = 1)`);
            await conn.commit();
        } catch(e) {}

        // 3. Migrações: adicionar colunas que podem não existir em tabelas já criadas
        const ALTER_COLUMNS = [
            `ALTER TABLE CANAL_MENSAGENS ADD (MEDIA_MIMETYPE VARCHAR2(100))`,
            `ALTER TABLE CANAL_MENSAGENS ADD (MEDIA_TYPE VARCHAR2(50))`,
            `ALTER TABLE CANAL_MENSAGENS ADD (MEDIA_URL VARCHAR2(1000))`,
            `ALTER TABLE CANAL_MENSAGENS ADD (ARQUIVO_LOCAL VARCHAR2(1000))`,
            `ALTER TABLE CANAL_MENSAGENS ADD (STATUS VARCHAR2(50))`,
            `ALTER TABLE CANAL_MENSAGENS ADD (LIDA CHAR(1) DEFAULT 'N')`,
            `ALTER TABLE CANAL_MENSAGENS ADD (TICKET_ID NUMBER)`,
            `ALTER TABLE CANAL_SAC_TICKETS ADD (NOTA_AVALIACAO NUMBER(1))`,
            `ALTER TABLE CANAL_SAC_TICKETS ADD (DATA_RESOLUCAO TIMESTAMP)`,
            `ALTER TABLE CANAL_TOKENS_EVOLUTION ADD (NOME_ATENDENTE VARCHAR2(100))`
        ];
        for (const alterSql of ALTER_COLUMNS) {
            try {
                await conn.execute(alterSql);
                console.log(`✅ [STARTUP] Coluna adicionada: ${alterSql.substring(0, 80)}...`);
            } catch (err) {
                // ORA-01430: column being added already exists in the table
                if (err.errorNum === 1430) {
                    // Ignora, já existe
                } else {
                    console.error(`⚠️ [STARTUP] Erro ao adicionar coluna: ${alterSql}`, err.message);
                }
            }
        }

        // 4. Criação de Índices e Atualizações de Constraints
        const UPDATES = [
            `CREATE INDEX IDX_PROSPECTS_CNPJ ON CANAL_PROSPECTS (CNPJ)`,
            `CREATE INDEX IDX_PROSPECTS_CIDADE ON CANAL_PROSPECTS (CIDADE)`
        ];
        for (const updateSql of UPDATES) {
            try {
                await conn.execute(updateSql);
                console.log(`✅ [STARTUP] Atualização executada: ${updateSql}`);
            } catch (err) {
                if (err.errorNum === 955 || err.errorNum === 1408) { // Já existe
                    // Ignora
                } else {
                    console.error(`⚠️ [STARTUP] Erro na atualização: ${updateSql}`, err.message);
                }
            }
        }

        // Atualização de Constraint (CANAL_SAC_TICKETS STATUS)
        try {
            const resCons = await conn.execute(`
                SELECT constraint_name, search_condition 
                FROM user_constraints 
                WHERE table_name = 'CANAL_SAC_TICKETS' AND constraint_type = 'C'
            `);
            for (const row of resCons.rows) {
                const name = row[0];
                const cond = row[1];
                if (cond && cond.includes('STATUS')) {
                    await conn.execute(`ALTER TABLE CANAL_SAC_TICKETS DROP CONSTRAINT ${name}`);
                }
            }
            await conn.execute(`
                ALTER TABLE CANAL_SAC_TICKETS 
                ADD CONSTRAINT CK_CANAL_SAC_TICKETS_STATUS 
                CHECK (STATUS IN ('ABERTO', 'EM ATENDIMENTO', 'FECHADO', 'FINALIZADO'))
            `);
            console.log(`✅ [STARTUP] Constraint STATUS de CANAL_SAC_TICKETS atualizada.`);
        } catch (err) {
            console.error(`⚠️ [STARTUP] Erro ao atualizar constraint CK_CANAL_SAC_TICKETS_STATUS:`, err.message);
        }

        // 5. Dados Iniciais
        try {
            const defaults = [
                ['REATIVACAO', 'Saudade', 'Olá, sentimos sua falta! Veja algumas ofertas especiais que separamos para você:'],
                ['REATIVACAO', 'Oferta Especial', 'Temos preços exclusivos para você que não compra há um tempo. Confira nossa lista:'],
                ['CATALOGO', 'Lançamentos', 'Confira nossos lançamentos deste mês no catálogo anexo!'],
                ['CATALOGO', 'Promoção', 'Preços especiais! Veja nosso catálogo de ofertas anexo.'],
                ['ROTAS', 'Confirmação de Visita', 'Olá, confirmo nossa visita agendada para hoje. Até logo!'],
                ['ROTAS', 'Aviso de Chegada', 'Olá, estou a caminho para nossa reunião!']
            ];
            for (const row of defaults) {
                await conn.execute(
                    `INSERT INTO CANAL_MENSAGENS_TEMPLATES (PAGINA, TIPO, TEMPLATE) 
                     SELECT :1, :2, :3 FROM DUAL 
                     WHERE NOT EXISTS (
                         SELECT 1 FROM CANAL_MENSAGENS_TEMPLATES 
                         WHERE PAGINA = :1 AND TIPO = :2
                     )`,
                    row,
                    { autoCommit: true }
                );
            }
            console.log("✅ [STARTUP] Templates padrão inicializados com sucesso.");
        } catch (err) {
            console.error(`⚠️ [STARTUP] Erro ao inicializar templates padrão:`, err.message);
        }

        console.log('🎉 [STARTUP] Banco de dados Oracle inicializado perfeitamente! Pronto para operar.');
    } catch (err) {
        console.error('❌ [STARTUP] Falha crítica na inicialização do Oracle:', err);
    } finally {
        if (conn) {
            try { await conn.close(); } catch (e) {}
        }
    }
}

module.exports = initializeOracleDatabase;
