const oracledb = require('oracledb');
const fs = require('fs');
const path = require('path');

const TABLES = [
    `CREATE TABLE CANAL_ANALISE_CNPJ (
        CODCLI NUMBER PRIMARY KEY,
        CGCENT VARCHAR2(20),
        SITUACAO_CADASTRAL VARCHAR2(100),
        ATUALIZADO_POR VARCHAR2(50),
        DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE CANAL_MENSAGENS (
        ID_MENSAGEM VARCHAR2(255) PRIMARY KEY,
        CODUSUR VARCHAR2(50),
        TELEFONE_CLIENTE VARCHAR2(50),
        SENTIDO VARCHAR2(20),
        TEXTO CLOB,
        DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        MEDIA_URL VARCHAR2(1000),
        MEDIA_TYPE VARCHAR2(50),
        MEDIA_MIMETYPE VARCHAR2(100),
        ARQUIVO_LOCAL VARCHAR2(1000),
        STATUS VARCHAR2(50),
        LIDA CHAR(1) DEFAULT 'N'
    )`,
    `CREATE TABLE CANAL_TOKENS_EVOLUTION (
        CODUSUR VARCHAR2(50) PRIMARY KEY,
        NOME_INSTANCIA VARCHAR2(100),
        TOKEN VARCHAR2(255),
        URL_INSTANCIA VARCHAR2(255),
        STATUS VARCHAR2(50),
        DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE JCWEBHOOK (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        DT_REQUISICAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONTEUDO CLOB,
        ORIGEM VARCHAR2(50) DEFAULT 'whats'
    )`,
    `CREATE TABLE CANAL_WEBHOOK_STATE (
        ID NUMBER PRIMARY KEY,
        LAST_PROCESSED_ID NUMBER DEFAULT 0
    )`,
    `CREATE TABLE CANAL_CONFIGURACOES (
        CHAVE VARCHAR2(100) PRIMARY KEY,
        VALOR VARCHAR2(4000)
    )`,
    `CREATE TABLE CANAL_ROTAS (
        CODUSUR VARCHAR2(50),
        DIASEMANA NUMBER,
        CODCLI NUMBER,
        SEQUENCIA NUMBER,
        INTERACAO VARCHAR2(100),
        PRIMARY KEY (CODUSUR, DIASEMANA, CODCLI)
    )`,
    `CREATE TABLE CANAL_AGENDAMENTO_STATUS (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        ARQUIVO_PATH VARCHAR2(255),
        LEGENDA VARCHAR2(4000),
        DATA_PROGRAMADA TIMESTAMP,
        VENDEDORES_DESTINO CLOB,
        CRIADO_POR VARCHAR2(50),
        STATUS_ENVIO VARCHAR2(50) DEFAULT 'PENDENTE'
    )`,
    `CREATE TABLE CANAL_LOG_ALTERACAO_VENDEDOR (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        CODCLI NUMBER,
        VENDEDOR_ANTERIOR VARCHAR2(50),
        VENDEDOR_NOVO VARCHAR2(50),
        ALTERADO_POR VARCHAR2(50),
        DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE CANAL_REATIVACAO_FILA (
        ID NUMBER PRIMARY KEY,
        CODCLI NUMBER,
        TELEFONE VARCHAR2(50),
        CODUSUR VARCHAR2(50),
        MENSAGEM_TXT CLOB,
        CODATV1 NUMBER,
        STATUS VARCHAR2(50),
        DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE CANAL_TEMPLATES (
        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TITULO VARCHAR2(100),
        TEXTO CLOB
    )`,
    `CREATE TABLE CANAL_AVISOS (
        ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TITULO VARCHAR2(200),
        TEXTO CLOB,
        DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        STATUS VARCHAR2(20)
    )`,
    `CREATE TABLE CANAL_VISITAS (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        CODCLI NUMBER,
        CODUSUR VARCHAR2(50),
        TIPO VARCHAR2(50),
        DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        STATUS VARCHAR2(50),
        OBSERVACAO VARCHAR2(4000),
        LATITUDE NUMBER,
        LONGITUDE NUMBER,
        ENDERECO_VINCULADO VARCHAR2(4000),
        IMAGEM_URL VARCHAR2(4000),
        RETORNO VARCHAR2(4000),
        SINALIZADO_VENDEDOR CHAR(1) DEFAULT 'N'
    )`,
    `CREATE TABLE CANAL_MENSAGENS_AUT_CONFIG (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        TIPO_REGRA VARCHAR2(100),
        DIAS_GATILHO NUMBER,
        DIA_ESPECIFICO NUMBER,
        TEMPLATE_MENSAGEM CLOB,
        ATIVO CHAR(1) DEFAULT 'S'
    )`
];

async function initializeOracleDatabase() {
    console.log('[DB-INIT] Iniciando verificação de tabelas no Oracle...');
    let conn;
    try {
        conn = await oracledb.getConnection({
            user: process.env.ORACLE_USER,
            password: process.env.ORACLE_PASS,
            connectString: process.env.ORACLE_CONN_STR
        });

        // DROP wrong tables from previous bad init (if they exist)
        try { await conn.execute(`DROP TABLE JCWEBHOOK CASCADE CONSTRAINTS`); } catch(e){}
        try { await conn.execute(`DROP TABLE CANAL_AGENDAMENTO_STATUS CASCADE CONSTRAINTS`); } catch(e){}
        try { await conn.execute(`DROP TABLE CANAL_WEBHOOK_STATE CASCADE CONSTRAINTS`); } catch(e){}

        // 1. Criar Tabelas
        for (const sql of TABLES) {
            try {
                await conn.execute(sql);
                const tableName = sql.match(/CREATE TABLE (\w+)/)[1];
                console.log(`[DB-INIT] Tabela ${tableName} criada com sucesso.`);
            } catch (err) {
                // Erro 955: "name is already used by an existing object"
                if (err.errorNum === 955) {
                    // Ignora, já existe
                } else {
                    console.error(`[DB-INIT] Erro ao criar tabela:\n${sql}\nErro:`, err.message);
                }
            }
        }

        // 2. Criar Views
        const viewsFilePath = path.join(__dirname, '../database/winthor_views.sql');
        if (fs.existsSync(viewsFilePath)) {
            const viewsSql = fs.readFileSync(viewsFilePath, 'utf8');
            // Split por ';'
            const statements = viewsSql.split(';').map(s => s.trim()).filter(s => s.length > 0);
            
            for (const stmt of statements) {
                if (stmt.toUpperCase().startsWith('CREATE')) {
                    try {
                        await conn.execute(stmt);
                    } catch (err) {
                        console.error(`[DB-INIT] Erro ao criar view: ${stmt.substring(0, 50)}...`, err.message);
                    }
                }
            }
            console.log('[DB-INIT] Views do Winthor (VW_CANAL_*) recriadas/validadas com sucesso.');
        } else {
            console.warn('[DB-INIT] Arquivo winthor_views.sql não encontrado.');
        }

        // Initialize state table if empty
        try {
            await conn.execute(`INSERT INTO CANAL_WEBHOOK_STATE (ID, LAST_PROCESSED_ID) SELECT 1, 0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CANAL_WEBHOOK_STATE WHERE ID = 1)`);
            await conn.commit();
        } catch(e) {}

        console.log('[DB-INIT] Inicialização do banco de dados Oracle concluída!');
    } catch (err) {
        console.error('[DB-INIT] Falha na inicialização do Oracle:', err);
    } finally {
        if (conn) {
            try { await conn.close(); } catch (e) {}
        }
    }
}

module.exports = initializeOracleDatabase;
