-- Tabela para armazenar leads prospectados
CREATE TABLE CANAL_PROSPECTS (
    ID VARCHAR2(50) DEFAULT RAWTOHEX(SYS_GUID()) PRIMARY KEY,
    NOME_FANTASIA VARCHAR2(255) NOT NULL,
    RAZAO_SOCIAL VARCHAR2(255),
    CNPJ VARCHAR2(20),
    TELEFONE VARCHAR2(100),
    ENDERECO VARCHAR2(500),
    CIDADE VARCHAR2(100),
    ESTADO VARCHAR2(2),
    LATITUDE VARCHAR2(50),
    LONGITUDE VARCHAR2(50),
    ORIGEM VARCHAR2(50), -- 'CNPJA' ou 'GEOAPIFY'
    RAMO_ATIVIDADE VARCHAR2(100),
    HAS_WHATSAPP VARCHAR2(1) DEFAULT 'P', -- S (Sim), N (Não), P (Pendente)
    DATA_CADASTRO DATE DEFAULT SYSDATE
);

-- Índices para busca rápida
CREATE INDEX IDX_PROSPECTS_CNPJ ON CANAL_PROSPECTS (CNPJ);
CREATE INDEX IDX_PROSPECTS_CIDADE ON CANAL_PROSPECTS (CIDADE);

EXIT;
