CREATE TABLE PCCLIENT_GEOLOCACAO (
    CODCLI NUMBER PRIMARY KEY,
    ENDERECO_COMPLETO VARCHAR2(500),
    LATITUDE VARCHAR2(50),
    LONGITUDE VARCHAR2(50),
    STATUS VARCHAR2(1) DEFAULT 'P',
    DATA_CONSULTA DATE,
    ERRO_MOTIVO VARCHAR2(500)
);

COMMENT ON TABLE PCCLIENT_GEOLOCACAO IS 'Tabela de estagio para geolocalizacao de clientes';
COMMENT ON COLUMN PCCLIENT_GEOLOCACAO.STATUS IS 'P: Pendente, O: Ok, E: Erro';
