-- Arquivo de Views do Winthor
-- Estas views abstraem as tabelas brutas do sistema para facilitar o acesso da API.

-- 1. View de Produtos Ativos
CREATE OR REPLACE VIEW VW_CANAL_PRODUTOS AS
SELECT 
    P.CODPROD,
    P.DESCRICAO,
    P.CODFAB,
    P.MARCA,
    E.UNIDADE AS TIPO_EMBALAGEM,
    E.QTUNIT AS QUANTIDADE_EMBALAGEM,
    E.CODAUXILIAR AS CODIGO_BARRAS,
    P.PESOBRUTO,
    P.PESOLIQ,
    P.VOLUME,
    F.CODFILIAL
FROM PCPRODUT P
JOIN PCPRODFILIAL F ON P.CODPROD = F.CODPROD
JOIN PCEMBALAGEM E ON P.CODPROD = E.CODPROD AND F.CODFILIAL = E.CODFILIAL
WHERE P.OBS2 <> 'FL'
  AND F.ENVIARFORCAVENDAS = 'S'
  AND E.ENVIAFV = 'S';

-- 2. View de Estoque Simplificado
CREATE OR REPLACE VIEW VW_CANAL_ESTOQUE AS
SELECT 
    CODPROD,
    CODFILIAL,
    QTESTGER AS ESTOQUE_GERAL,
    QTRESERV AS RESERVADO,
    QTBLOQUEADA AS BLOQUEADO,
    (QTESTGER - QTRESERV - QTBLOQUEADA) AS ESTOQUE_DISPONIVEL
FROM PCEST
WHERE (QTESTGER - QTRESERV - QTBLOQUEADA) > 0;

-- 3. View de PreÃ§os BÃ¡sicos
CREATE OR REPLACE VIEW VW_CANAL_PRECOS AS
SELECT 
    CODPROD,
    NUMREGIAO,
    PTABELA AS PRECO_TABELA,
    PVENDA AS PRECO_VENDA
FROM PCTABPR;

-- 4. View de AutenticaÃ§Ã£o de UsuÃ¡rios (Vendedores, Supervisores e Gerentes)
CREATE OR REPLACE VIEW VW_CANAL_USUARIOS AS
SELECT 
    U.CODUSUR,
    U.NOME,
    U.USURFTP,
    U.SENHAFTP,
    U.TIPOVEND,
    U.CODSUPERVISOR,
    S.NOME AS NOME_SUPERVISOR,
    CASE 
        WHEN G.CODGERENTE IS NOT NULL THEN 'GERENTE'
        WHEN S_CHECK.CODSUPERVISOR IS NOT NULL THEN 'SUPERVISOR'
        ELSE 'VENDEDOR'
    END AS CARGO
FROM PCUSUARI U
LEFT JOIN PCSUPERV S ON U.CODSUPERVISOR = S.CODSUPERVISOR
LEFT JOIN PCSUPERV S_CHECK ON U.CODUSUR = S_CHECK.CODSUPERVISOR
LEFT JOIN PCGERENTE G ON U.CODUSUR = G.CODGERENTE
WHERE U.BLOQUEIO = 'N' OR U.BLOQUEIO IS NULL;

-- 5. View de Carteira de Clientes (Vinculada aos Vendedores)
CREATE OR REPLACE VIEW VW_CANAL_CLIENTES AS
SELECT 
    C.CODCLI,
    C.CLIENTE,
    C.FANTASIA,
    C.CGCENT AS CNPJ,
    C.TELCELENT AS TELEFONE,
    C.CODUSUR1 AS VENDEDOR_PRINCIPAL,
    C.BLOQUEIO,
    C.LIMCRED AS LIMITE_CREDITO
FROM PCCLIENT C
-- Aqui pode-se adicionar filtros de bloqueio ou inatividade se existirem na sua regra, ex:
-- WHERE C.BLOQUEIO = 'N'
;

